# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-22 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('date', models.DateTimeField(verbose_name='\u0414\u0430\u0442\u0430')),
                ('is_hidden', models.BooleanField(verbose_name='\u0421\u043a\u0440\u044b\u0442\u0430\u044f \u0441\u0442\u0430\u0442\u044c\u044f')),
                ('is_deleted', models.BooleanField(verbose_name='\u0423\u0434\u0430\u043b\u0435\u043d\u043e')),
                ('is_published', models.BooleanField(verbose_name='\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d\u043e')),
                ('text', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442')),
                ('slug', models.CharField(max_length=255, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, upload_to=b'')),
            ],
            options={
                'verbose_name': '\u0421\u0442\u0430\u0442\u044c\u044f',
                'verbose_name_plural': '\u0421\u0442\u0430\u0442\u044c\u0438',
            },
        ),
        migrations.CreateModel(
            name='ArticleView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP')),
                ('view_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article', verbose_name='\u0421\u0442\u0430\u0442\u044c\u044f')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u043e\u0441\u043c\u043e\u0442\u0440',
                'verbose_name_plural': '\u041f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0420\u0443\u0431\u0440\u0438\u043a\u0430',
                'verbose_name_plural': '\u0420\u0443\u0431\u0440\u0438\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0422\u0435\u0433',
                'verbose_name_plural': '\u0422\u0435\u0433\u0438',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Rubric', verbose_name='\u0420\u0443\u0431\u0440\u0438\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='\u0422\u0435\u0433\u0438'),
        ),
    ]
